[package]
name = "aesti"
version = "0.3.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "GPL-2.0"
description = "Constant/fixed/invariant time aes implimentation (originally from Linux)"
keywords = [ "crypto", "aes", "no_std"]
include = [ "Cargo.toml", "**/*.rs"]
repository = "https://github.com/jmesmon/aesti"
documentation = "https://docs.rs/aesti"
categories = [ "cryptography", "no-std" ]

[dependencies]
index-fixed = "0.3"

[dev-dependencies]
openssl = "0.10"
quickcheck = "0.8"
hex = "0.3"
fmt-extra = "0.2"
rand = "0.6"
